services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-php
    container_name: app-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - vpc-network-php

  server:
    image: nginx:stable-alpine3.19
    container_name: server-nginx
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - vpc-network-php

networks:
  vpc-network-php:
    driver: bridge
