services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-php
    container_name: app-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - vpc-network-php

networks:
  vpc-network-php:
    driver: bridge
